sudo: required

services: mongodb

language: python
python:
  - "3.9.1" 
  - pypy

# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls


# the below is to add an artifical wait for mongodb
# to start as per travis-ci doc http://docs.travis-ci.com/user/database-setup/
before_script:
    - sleep 15
    - mongo mydb_test --eval 'db.addUser("travis", "test");'

# command to run tests
script:
    coverage3 run --source=app -m unittest discover

after_success:
    coveralls
