sudo: required

services:
  - docker
  - mongodb

language: python
python:
  - "2.7"



# command to install dependencies
install:
  - pip install -r requirements.txt



# the below is to add an artifical wait for mongodb
# to start as per travis-ci doc http://docs.travis-ci.com/user/database-setup/
before_script:
    - sleep 15
    - mongo mydb_test --eval 'db.addUser("travis", "test");

# command to run tests
script:
    python -m unittest discover
